version: '3'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:22.7
    restart: on-failure
    environment:
      CLICKHOUSE_DB: uptrace
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'localhost:8123/ping']
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - ../../config/clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml      
      - ch_data:/var/lib/clickhouse
    # network_mode: host
    ports:
      - '8123:8123'
      - '9000:9000'
    networks:
      - clickhouse-net
    extra_hosts:
     - 'host.docker.internal:host-gateway'

  uptrace:
    image: 'uptrace/uptrace:latest'
    #image: 'uptrace/uptrace-dev:latest'
    volumes:
      - uptrace_data:/var/lib/uptrace
      - ../../config/uptrace.yml:/etc/uptrace/uptrace.yml
    #network_mode: host
    ports:
      - '14317:14317' # OTLP
      - '14318:14318' # UI and HTTP API
    networks:
      - clickhouse-net
    environment:
      - UPTRACE_DB_FILE=/var/lib/uptrace/uptrace.sqlite3
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      clickhouse:
        condition: service_healthy

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.58.0
    restart: on-failure
    volumes:
      - ../../config/otel-collector.yaml:/etc/otelcol-contrib/config.yaml
    network_mode: host

  alertmanager:
    image: prom/alertmanager:v0.24.0
    restart: on-failure
    volumes:
      - ./alertmanager/:/etc/alertmanager/
      - alertmanager_data:/alertmanager
    ports:
      - 9093:9093
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  # jaeger-agent:
  #   image: jaegertracing/jaeger-agent:latest
  #   command: ['--reporter.grpc.host-port=localhost:14250']
  #   network_mode: host

  # jaeger-hot-rod:
  #   image: jaegertracing/example-hotrod:latest
  #   command: ['all']
  #   network_mode: host
  #   environment:
  #     - JAEGER_AGENT_HOST=localhost
  #     - JAEGER_AGENT_PORT=6831
  #   depends_on:
  #     - jaeger-agent

volumes:
  uptrace_data:
    driver: local
  ch_data:
    driver: local
  alertmanager_data:
    driver: local

networks:
  clickhouse-net:
    external: false
